# Generated by Django 4.2.3 on 2023-07-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('genre', models.TextField()),
                ('star', models.IntegerField()),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
