# Generated by Django 4.2.3 on 2023-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.FloatField(),
        ),
    ]
