# Generated by Django 4.2.3 on 2023-07-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.IntegerField(null=True),
        ),
    ]
